services:
  frontend-admin:
    build: frontend-admin
    init: true
    ports:
      - "5173:5173"
  backend:
    build: backend
    init: true
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: appointment-system
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
