services:
  frontend-admin:
    build: frontend-admin
    init: true
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 5173:5173
    volumes:
      - ./frontend-admin/schema.gql:/app/schema.gql
      - ./frontend-admin/src:/app/src
      - ./frontend-admin/public:/app/public
  backend:
    build: backend
    init: true
    ports:
      - 3000:3000
    volumes:
      - ./backend/migrations:/app/migrations
      - ./backend/src:/app/src
    environment:
      DB_HOST: "db"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: appointment-system
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
