version: '3'

tasks:
  start:
    desc: 'Starts the application'
    deps:
      - installPackages
    cmds:
      - touch ./backend/src/schema.gql
      - docker compose up --build
    interactive: true
  installBackendPackages:
    desc: 'Installs backend packages'
    dir: backend
    cmds:
      - npm install
  installFrontendAdminPackages:
    desc: 'Installs frontend packages'
    dir: frontend-admin
    cmds:
      - yarn install
  installPackages:
    desc: 'Installs backend and frontend packages'
    deps:
      - installBackendPackages
      - installFrontendAdminPackages
    silent: true
  addMigration:
    desc: 'Adds a new migration'
    dir: backend
    requires:
      vars: [NAME]
    cmds:
      - npm run typeorm migration:create ./migrations/{{.NAME}}
  clean:
    desc: 'Cleans the application'
    cmds:
      - docker compose down -v
    interactive: true